//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ogrencisistemiEntities : DbContext
    {
        public ogrencisistemiEntities()
            : base("name=ogrencisistemiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<lesson_teacher> lesson_teacher { get; set; }
        public virtual DbSet<lessons> lessons { get; set; }
        public virtual DbSet<login> login { get; set; }
        public virtual DbSet<position> position { get; set; }
        public virtual DbSet<studentlessons> studentlessons { get; set; }
        public virtual DbSet<students> students { get; set; }
    }
}
