//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.login = new HashSet<login>();
            this.lesson_teacher = new HashSet<lesson_teacher>();
        }
    
        public int id { get; set; }
        public string employee_name { get; set; }
        public byte[] employee_password { get; set; }
        public string employee_email { get; set; }
        public string employee_tckn { get; set; }
        public string employee_phoneno { get; set; }
        public bool emoployee_status { get; set; }
        public Nullable<System.DateTime> employee_lastchange { get; set; }
        public int employee_position { get; set; }
    
        public virtual position position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<login> login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lesson_teacher> lesson_teacher { get; set; }
    }
}
