//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lesson_teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lesson_teacher()
        {
            this.studentlessons = new HashSet<studentlessons>();
        }
    
        public int id { get; set; }
        public Nullable<int> lesson_id { get; set; }
        public Nullable<int> teacher_id { get; set; }
        public string donem { get; set; }
        public Nullable<System.DateTime> lesson_teacher_lastchange { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual lessons lessons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studentlessons> studentlessons { get; set; }
    }
}
