//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lessons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lessons()
        {
            this.lesson_teacher = new HashSet<lesson_teacher>();
        }
    
        public int id { get; set; }
        public string lesson_name { get; set; }
        public string lesson_code { get; set; }
        public int akts { get; set; }
        public Nullable<System.DateTime> lesson_lastchange { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lesson_teacher> lesson_teacher { get; set; }
    }
}
