//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public int id { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<int> teacher_id { get; set; }
        public Nullable<bool> login1 { get; set; }
        public Nullable<System.DateTime> login_lastlogin { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual students students { get; set; }
    }
}
