//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class students
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public students()
        {
            this.login = new HashSet<login>();
            this.studentlessons = new HashSet<studentlessons>();
        }
    
        public int id { get; set; }
        public string student_no { get; set; }
        public byte[] student_password { get; set; }
        public string student_name { get; set; }
        public string student_email { get; set; }
        public string student_tckn { get; set; }
        public string student_phoneno { get; set; }
        public bool student_status { get; set; }
        public Nullable<System.DateTime> student_lastchange { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<login> login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studentlessons> studentlessons { get; set; }
    }
}
