//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentlessons
    {
        public int id { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<int> teacher_lesson { get; set; }
        public string grade { get; set; }
        public Nullable<System.DateTime> studentlesson_lastchange { get; set; }
    
        public virtual lesson_teacher lesson_teacher { get; set; }
        public virtual students students { get; set; }
    }
}
